# -*- coding: utf-8 -*-
"""csp_graphcoloring.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P0SCPQ7j0TdYFqhKAZPejzS68mOEuVAj
"""

# Import libraries
import networkx as nx
import matplotlib.pyplot as plt

# -------- CSP Class --------
class CSP:
    def __init__(self, variables, domains, neighbors):
        self.variables = variables
        self.domains = domains
        self.neighbors = neighbors

    def is_consistent(self, var, value, assignment):
        # Check if any neighbor has the same color
        for neighbor in self.neighbors[var]:
            if neighbor in assignment and assignment[neighbor] == value:
                return False
        return True

    def backtrack(self, assignment):
        if len(assignment) == len(self.variables):
            return assignment

        # Select unassigned variable
        for var in self.variables:
            if var not in assignment:
                break

        # Try all colors
        for value in self.domains[var]:
            if self.is_consistent(var, value, assignment):
                assignment[var] = value
                result = self.backtrack(assignment)
                if result:
                    return result
                assignment.pop(var)  # Backtrack

        return None

# -------- Graph Definition --------
# Create graph using networkx
G = nx.Graph()

edges = [('A','B'), ('A','C'), ('B','C'), ('B','D'), ('C','E'), ('D','E')]
G.add_edges_from(edges)

variables = list(G.nodes())
colors = ['red', 'green', 'blue', 'yellow']
domains = {var: colors for var in variables}
neighbors = {var: list(G.neighbors(var)) for var in variables}

# -------- Solve CSP --------
csp = CSP(variables, domains, neighbors)
solution = csp.backtrack({})

# -------- Output --------
if solution:
    print("Graph Coloring Solution:")
    for node, color in solution.items():
        print(f"{node} -> {color}")

    # Visualize graph
    node_colors = [solution[node] for node in G.nodes()]
    pos = nx.spring_layout(G, seed=42)  # positions for nodes
    nx.draw(G, pos, with_labels=True, node_color=node_colors, node_size=2000, font_size=15)
    plt.title("Graph Coloring using CSP (4 Colors)")
    plt.show()
else:
    print("No solution found.")